# Inherit from base config
defaults:
  - config
  - _self_

data:
  train_ratio: 0.75
  val_ratio: 0.15  # test_ratio will be 0.15

training:
  batch_size: 200
  max_epochs: 2
  accelerator: "cpu"
  num_workers: 1

logging:
  log_every_n_steps: 1 

model:
  layer_widths: [32, 32, 32, 32]
  dropout: 0.